### ISSUE TITLE
Feature Request: Hide pages to all by default

### ISSUE THREAD

**Issue by danvim** [Requarks/wiki-v1#141]
I would like to use Wiki.js as an internal knowledge base. However, there are times when something should be hidden to users in this case.

Can a new feature be added to hide pages by default, unless permission is given to users to view them?

**Comment by searhiy** [comment]
Hello,

Do you have any update for this feature request?

Thanks

**Comment by NGPixel** [comment]
Upgrade to v2 which includes this feature. v1 is no longer being updated.
