### ISSUE TITLE
wiki configure wizard can't find JS directory

### ISSUE THREAD

**Issue by benwolski** [Requarks/wiki-v1#144]
Hi. I think I successfully pointed my subdomain to the wiki config wizard running on port 3000, but when I navigate to that page it doesn't find the config JS.

here's what shows up:

![image](https://user-images.githubusercontent.com/570819/49752287-c5c8cb00-fc64-11e8-97e1-5de8b32faed2.png)

Result: GET https://test.justicewiki.org/js/vendor.js net::ERR_ABORTED 404

I'm a beginner, so I'm sure the issue is with my configuration of the proxy or permissions or something. Any advice?

**Comment by PureNukage** [comment]
I am having the same issue. I load to "http://localhost:3000" and see very un-styled page, absolutely no wizard configuration happening. 

I have tried all different variations in the config.yml but it doesn't make sense for me to even open that, the wizard is supposed to create/edit that file with me?

**Comment by PureNukage** [comment]
Attempting to install Wiki.js has proven to be an exercise in insanity. 

First I had issues with the one-line powershell command to install, error message coming was 
`Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel.`

Then I went to installing it using the actual script, found here: https://github.com/Requarks/wiki/issues/421

The script would cancel after Step 4 reporting a command-line error with 7-Zip. After not solving this, I instead attempted to install manually using the directions at the bottom of the page here: https://docs-legacy.requarks.io/wiki/install

I got rid of the "sample" from the config.yml and ran "node wiki configure". 

It appears with no CSS and no way to actually continue through the wizard. "node wiki start" leads to another unstyled page wanting me to log in. 



Things of note: I have MongoDB installed, created a database named "wiki", the service is running. I do not have apache installed, don't NEED or even want the server to be internet, intra works for what I need. 

It seems being a rocket scientist at NASA is needed to install this garbage.

**Comment by NGPixel** [comment]
@PureNukage You are seeing an unstyled page because you didn't set the proper `host`, as explained in the docs: https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css

If you use `http://localhost:3000` to access your wiki, then that should be the value.

As for the powershell error, Windows use TLS 1.0 by default, which is no longer supported by the website. I updated the install command to force TLS 1.2 before downloading the install script.

As for the error you got with 7-zip, I could not replicate it on my machine. Make sure you install into a folder you have the proper permissions or run powershell as admin.

**Comment by PureNukage** [comment]
Here's my config.yml

![image](https://user-images.githubusercontent.com/31448973/51047638-a0deb500-158e-11e9-87e8-baa1ec5900ec.png)

**Comment by NGPixel** [comment]
@PureNukage According to the screenshot of the file listing, you are using the repository contents and not a release build. So you're definitely going to run into issues as you're missing some generated files.

If you can't use the install scripts and want to do it manually, you got to download the packages from the Releases page:

https://github.com/Requarks/wiki/releases/tag/v1.0.102

- Delete all files / folders first, to start fresh
- Delete all collections in the MongoDB database
- Download and extract wiki-js.tar.gz and node_modules.tar.gz (into its node_modules subfolder)
- Make sure you're running Node.js 6.11.1 or later, up to Node 10.x
- Rename config.sample.yml to config.yml
- Run `node wiki configure`

**Comment by PureNukage** [comment]
I downloaded the node_modules and the wiki-js. I extracted them from the gz as well as the tar. 

I tried to run 'node wiki configure' and I had an error, missing module bluebird. I ran 'npm install' and eventually got this error. 

`npm ERR! Refusing to delete C:\Users\rbstenso\Documents\web design\wikijs\node_modules\i18next-node-fs-backend\node_modules\.bin\js-yaml: is outside C:\Users\rbstenso\Documents\web design\wikijs\node_modules\i18next-node-fs-backend\node_modules\js-yaml and not a link
npm ERR! File exists: C:\Users\rbstenso\Documents\web design\wikijs\node_modules\i18next-node-fs-backend\node_modules\.bin\js-yaml
npm ERR! Move it away, and try again.`

**Comment by PureNukage** [comment]
Got it working, had a doozy of a time. Looks and feels nice thus far, only thing left is that the host computer sees a lot of "modal.xxxxx" everywhere
