### ISSUE TITLE
Where to find documentation ?

### ISSUE THREAD

**Issue by stefaanv** [Requarks/wiki-v1#154]
I'm starting to use wiki.js but have a hard time finding user documentation about syntax, side menus, folder structure, page naming, etc.  It seems I'm always referred to https://docs.requarks.io/wiki/ which is very short and only informs about the installation of wiki.js.

Where can I find informative usage documentation ?

**Comment by NGPixel** [comment]
User documentation is lacking for v1. This will be improved in v2.

For syntax, you can check out any Markdown guide. e.g.:
https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

The side menus are generated from the headers in the page. As long as you define headers, starting with the top level (e.g. `# Header`), they will appear in the sidebar.

Folder structure will follow whatever you use as the path of your pages. So if you create a new page at `/foo/bar/page`, the corresponding folder structure will be generated. If you want the "Back" link to appear, you need to create pages with the same name as the folder. So in the previous example, you'd have to create a page `/foo` and `/foo/bar` to get the back links in `/foo/bar/page`.
