### ISSUE TITLE
How to migrate wiki.js to another server. 

### ISSUE THREAD

**Issue by vuduytu** [Requarks/wiki-v1#158]
I'm using wiki.js on centos7 vps. I want to migrate wiki.js to another centos7 server. Could you support me!

**Comment by NGPixel** [comment]
Install Wiki.js on the new server using the standard instructions. Then simply copy over your config.yml and the repo folder.

**Comment by pbdco** [comment]
For anyone looking for this, this has been solved and you can find the instructions at https://github.com/Requarks/wiki/issues/2403 🙂 
@vuduytu
