### ISSUE TITLE
Wiki.js can't handle force push

### ISSUE THREAD

**Issue by marianhlavac** [Requarks/wiki-v1#160]
### Actual behavior

After force pushing into the remote repository, Wiki.js fails to keep up and sync brokes.

### Expected behavior

After force pushing, Wiki.js does any action (desync warning, trying to pull, asking for reset)

### Steps to reproduce the behavior

1. force push into the remote repo
2. restart wikijs server

**Comment by mozboz** [comment]
Presumably because local wikijs repo needs manual attention to resolve against the remote repo? Did you trying checking out git status or git pull on the local wikijs repo?
