### ISSUE TITLE
Use frontmatter instead of HTML comments

### ISSUE THREAD

**Issue by mmajko** [Requarks/wiki-v1#161]
HTML comments aren't hidden in every Markdown renderer, you should avoid them. On Bitbucket the comments are visible and it's very ugly.

Using Frontmatter for metadata is more civilized than mixing meaningless HTML comments in Markdown text. It is widely supported (or definitely more widely than HTML comments).

https://jekyllrb.com/docs/front-matter/

**Comment by NGPixel** [comment]
This is now the case in 2.0.
