### ISSUE TITLE
Webserver does not seem to send data from docker container to host

### ISSUE THREAD

**Issue by bensta** [Requarks/wiki-v1#163]
I try to run wiki.js using docker compose on my macbook with an up to date MacOS Mojave

### Actual behavior
- When I try to open the web interface of wiki.js using localhost:8080 within Firefox on the **host**, the browser is stuck loading forever, no data seams to come from the server.
- When I run wget localhost:8080 on the **host**, i get
```
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 302 Found
Location: /login [following]
--2019-02-12 18:37:05--  http://localhost:8080/login
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
```
- When I run wget localhost:8080 **within the docker container**, i get
```
index.html            99% |********************************************* |  2732   - stalled -
```
However, index.html seems to be fetched from localhost anyway (despite the stall at the end)
### Expected behavior
I expected to see the web interface of wiki.js
### Steps to reproduce the behavior
Run docker-compose up using the following config files:
- [docker compose file](https://pastebin.com/AVc0LMWq)
- [wiki.js config file](https://pastebin.com/5ESuMKjQ)
--> for the port, i chose port 8080 everywhere (inside the container and outside) to avoid any confusions there. 

Open a browser on the host and visit localhost:8080

It seems as if some sort of Firewall drops packages somewhere between host and docker image. My MacBook firewall is deactivated however. 

Any help is appreciated!

**Comment by NGPixel** [comment]
- Have you tried on another port?
- Check the logs folder inside the container (`/logs`) for errors.

**Comment by bensta** [comment]
Just tried port 3000 everywhere, same result. 

The logs:
**[wiki-stderr.log](https://pastebin.com/HSaAj04d)**
Errors that are present: 
- failed to connect to mongoDB the first time (seems to work later, see note below)
- failed to connect to remote git (expected, since I did not enter correct github credentials)

**Note**: The [output](https://pastebin.com/d5rApjp8) from the mongoDB container shows active, accepted connections, so the mongoDB issue seems to be solved later in the startup process I guess (see line 37-41 in the output on pastebin)

**[wiki-stdout.log](https://pastebin.com/3aW2Nx31)**
- seems ok

**Comment by NGPixel** [comment]
While you might get active connections in MongoDB, it relies on a pool of connections. If some of them are failing, there's a good chance some pages will fail to load.

Try starting MongoDB as a separate container, wait for it to be fully started. Then start a separate container with Wiki.js pointing to that DB.

**Comment by bensta** [comment]
I ran: 
First:
`docker run --name wikidb -d mongo`
Then:
`docker run -p 3000:3000 --name wikijs  --link wikidb:wikijs  -e "WIKI_ADMIN_EMAIL=admin@example.com" -v /Users/johndoe/wiki/dockerfile/config.yml:/var/wiki/config.yml requarks/wiki`

it worked. 
I assume, that some sort of health check should be included in the docker compose file to check if mongoDB is ready, what is your take on this?

**Comment by NGPixel** [comment]
This is already the case in 2.0.
