### ISSUE TITLE
Config wizard errors when remote repository is empty

### ISSUE THREAD

**Issue by Altreus** [Requarks/wiki-v1#164]
### Actual behavior

During configuration wizard, ability to pull master appears to be a heuristic for whether the remote git repository is working. It is necessary to create a dummy file in the repo before the wizard will complete.

### Expected behavior

Wizard should expect remote repository to be new and thus not contain any refs.

### Steps to reproduce the behavior

* Begin brand-new wiki.js installation
* All prerequisites met
* Launch and connect to configuration wizard
* Create blank repository on github
* Provide credentials for this repository during configuration wizard

Wizard breaks at this point with error about remote ref `master`.

* Create any file at all on the github repo and commit it (the links on the github page suffice)

Wizard will now continue.

**Comment by NGPixel** [comment]
v1 requires the remote to be initialized first.

Upcoming v2 handles uninitialized repos correctly.
