### ISSUE TITLE
How do I modify background images of the login page

### ISSUE THREAD

**Issue by symsymmas** [Requarks/wiki-v1#166]
### Actual behavior
There are background images like buildings and seats on log-in Web page.

### Expected behavior
Get my own background images on this log-in Web page.
Would I modify the source code?
Do I need to changes images in a directory to get my own background on my log-in Web page?

### Steps to reproduce the behavior
Connect to http://wiki.js.web.site/login

**Comment by NGPixel** [comment]
The images can be found in the `assets/images` folder. Simply replace them with your own images.

**Comment by symsymmas** [comment]
Thank you.
