### ISSUE TITLE
Displaying Old Page Data

### ISSUE THREAD

**Issue by io-craft** [Requarks/wiki-v1#171]
Wiki-V1
MongoDB 3.4

So, in the "normal view" it shows a page version from like several days ago. 

Whereas the "source view" version shows the correct page. And the correct page is in the repository. 

Where is this old data even coming form? What is going on? 

Super annoying, and that coupled with massive issues getting it setup, this has been quite the chore for very few features. 

I love the interface, and simplicity... but this is a non starter. I can't even add content at this point.

![image](https://user-images.githubusercontent.com/47536665/52926885-596de600-32fd-11e9-8f6d-fd22779523a3.png)

![image](https://user-images.githubusercontent.com/47536665/52926905-815d4980-32fd-11e9-9334-84165ac5782e.png)

**Comment by NGPixel** [comment]
Try to delete your `data/` folder and restart Wiki.js.

**Comment by io-craft** [comment]
That did the trick 100%! Thank you!

**Comment by NGPixel** [comment]
- What is the server OS / version or docker?
- Is git enabled?
- Do you have any errors in the logs?

**Comment by io-craft** [comment]
Ubuntu 18.04
Node v10.15.1
Mongo 4.0 Server (Mongo Atlas Cloud DB)

This is the only thing in the wiki-error log, after wiping the logs and stopping, starting, and reproducing the issue:

`You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "iocraft.bruteforces", key: { _id: 1 }, $
    at Function.MongoError.create (/storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Unhandled rejection MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "iocraft.bruteforces$
    at Function.MongoError.create (/storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "iocraft.bruteforces", key: { _id: 1 }, $
    at Function.MongoError.create (/storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at args.(anonymous function) (/storage/bot/node_modules/event-loop-inspector/index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Unhandled rejection MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "iocraft.bruteforces$
    at Function.MongoError.create (/storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
`

**Comment by io-craft** [comment]
I am really sorry. I think it was my derp. I have a git routine for the Wiki itself, and it appears to have been pulling down the data/ directory every time I wiped it. 

Everything is functional after disabling that custom cron for my Wiki.js repository. 

My fault, and my apologies!
