### ISSUE TITLE
[query] Can I modify the wiki via Git?

### ISSUE THREAD

**Issue by kwill** [Requarks/wiki-v1#173]
Is it possible to modify the wiki via Git. For example with the following procedure, or something like it?

1. Clone Git repo
2. Commit changes locally
3. Push changes to Git repo
4. Changes are now visible via GUI

If not, is this feature planned for 2.0? (I couldn't find a reference to it.)

**Comment by kwill** [comment]
Associated feature request (if it isn't already supported) https://requests.requarks.io/wiki/p/git-based-workflow

**Comment by NGPixel** [comment]
This is already possible in v1 (and the upcoming v2)

**Comment by kwill** [comment]
@NGPixel Thanks for the confirmation!

I assume this requires direct access and push rights on the Git repo. Is there any documentation on setting this up in a GitLab / GitHub style environment, where you don't want to give everybody those kind of permissions?

Do Git users need to worry about the synching operation? The nightmare here is a Git push overriding a GUI change, or vice versa.

**Comment by NGPixel** [comment]
https://docs.requarks.io/wiki/install/installation/git#providers

The overwriting issue will be better handled in v2. For v1 you need to use extra precautions as to not overwrite content before the sync occurs (every 5 mins).

**Comment by kwill** [comment]
@NGPixel Thanks for the link and the precautions :+1: Very much appreciated.
