### ISSUE TITLE
Just displaying files

### ISSUE THREAD

**Issue by ZakShearman** [Requarks/wiki-v1#176]
I realise that this is most likely an issue in my setup but I did not know where I would be able to get support so I realised that this is the best place.

I am getting this when I try to go to the URL that I have set up for the wiki: https://i.zak.pink/19-02-10-49-26_191.png.

Any help appreciated.

**Comment by ZakShearman** [comment]
Ok, welp. Thanks for the help.

**Comment by winkelement** [comment]
Since you already have apache running you can simply use `ProxyPass` to route requests to your node app (wiki js). See [here](http://www.codingtricks.biz/run-nodejs-application-apache/) for example.
You have to change the port for wiki js from 80 to something else before.

You might consider using a dedicated reverse proxy for all your routing, check out [nginx](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04#prerequisites) or [haproxy](http://physalix.com/reverse-proxy-for-nodejs-in-production-with-apache2-haproxy-and-monit/).

**Comment by ZakShearman** [comment]
I have tried to set this up and I get 503 service currently unavailable.

**Comment by ZakShearman** [comment]
Are we able to speak somewhere that is not on GitHub issues so that it is easier for me to get this fixed in a location that has less hassle.

**Comment by ZakShearman** [comment]
> Since you already have apache running you can simply use `ProxyPass` to route requests to your node app (wiki js). See [here](http://www.codingtricks.biz/run-nodejs-application-apache/) for example.
> You have to change the port for wiki js from 80 to something else before.
> 
> You might consider using a dedicated reverse proxy for all your routing, check out [nginx](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04#prerequisites) or [haproxy](http://physalix.com/reverse-proxy-for-nodejs-in-production-with-apache2-haproxy-and-monit/).

I am getting a new VPS and I think I will be using this chance to switch to NGINX.

**Comment by FiyaFly** [comment]
> > Since you already have apache running you can simply use `ProxyPass` to route requests to your node app (wiki js). See [here](http://www.codingtricks.biz/run-nodejs-application-apache/) for example.
> > You have to change the port for wiki js from 80 to something else before.
> > You might consider using a dedicated reverse proxy for all your routing, check out [nginx](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04#prerequisites) or [haproxy](http://physalix.com/reverse-proxy-for-nodejs-in-production-with-apache2-haproxy-and-monit/).
> 
> I am getting a new VPS and I think I will be using this chance to switch to NGINX.

I've been digging into nginx a bit recently as well. I'm no master, but let me know how far you've gotten, or if you'd like a hand.
