### ISSUE TITLE
Site unreachable after docker-compose.

### ISSUE THREAD

**Issue by Rykee** [Requarks/wiki-v1#177]
### Actual behavior
After running docker-compose can't reach the site.

### Expected behavior
Should be able to reach the site.

### Steps to reproduce the behavior

I followed the tutorial on the site for the docker-compose.  

Here are my config files: 
[config.yml](https://pastebin.com/NWE6ubUr)
[docker-compose.yml](https://pastebin.com/W3hNV0iJ)

Logs: (wiki-stderr.log was empty)
[supervisord.log](https://pastebin.com/aua1xu3y)
[wiki-stdout.log](https://pastebin.com/Zgf62ZCm)
[mongodb](https://pastebin.com/fMLY1hXm)

I can ping both ways, and when I installed an Apache I could connect to that server.
I tried multiple ports, only difference was with port 3000, with this output:
![image](https://user-images.githubusercontent.com/11543371/53413452-4b3e5a80-39cc-11e9-8d49-d409912f7788.png)

I checked a few issues, but no suggestion helped so far.

 Edit: If I add http:// before the ip address on the port 3000 it loads normally(doesn't read the data from git tho). 

If I don't use docker it works(loads data from git properly too), but it would be nice to use docker. Any suggestions?

**Comment by Rykee** [comment]
Bump

**Comment by NGPixel** [comment]
https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css

**Comment by Rykee** [comment]
See edit from 28 days ago..
