### ISSUE TITLE
Question: Login with existing database

### ISSUE THREAD

**Issue by diedona** [Requarks/wiki-v1#188]
Hello,

I have been given a task to create a Wiki for one the projects of my emplyer. I am very into Wiki.js instead of coding "yet another wiki like system". However, there's a catch i am not finding the pieces to solve on my own.

The login must be integrated with the existing database. 

The wiki must be private and we don't want to recreate the user accounts "by hand". Is there a way to fit in a custom login, or at least some way to sync the users through an API endpoint once the wiki is instaled in my server? (any other ideas would fit, if possible).

The admin users are fine to be created "by hand" in the wiki system. We are only concerned about the regular users.

**Comment by NGPixel** [comment]
Use a solution like OAuth2 or LDAP to use the same login for multiple applications. Both are supported in Wiki.js.

**Comment by diedona** [comment]
Thanks @NGPixel
