### ISSUE TITLE
Wiki.js in docker container won't connect to mongodb

### ISSUE THREAD

**Issue by jamalbernhard** [Requarks/wiki-v1#198]
Sorry, this is just a call for help. I'm a mongodb noob and have very little docker experience as well. I installed mongodb just to try Wiki.js. The daemon seems to be running fine:
```
$ mongo
MongoDB shell version v4.0.9
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("f6a8a520-c5c3-4d28-af02-3fb8f4e7750a") }
...
```
I followed the instructions to fetch the Wiki.js docker image and run the container. It looks to be up and connects successfully to the Github repo I set up, according to the log. However I can't get it to connect to mongodb. From `/logs/wiki-stderr.log`:
```
2019-04-17T17:48:43.269Z - error: [AGENT] Failed to connect to MongoDB instance.
Unhandled rejection MongoError: failed to connect to server [localhost:27017]
on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]                                                                                   
```
I tried using both `db: mongodb://localhost:27017/wiki` and `db: mongodb://127.0.0.1:27017/wiki` explicitly in my `config.yml`. I tried creating the `wiki` db in mongo. I also tried downloading and using mongodb's docker image instead of the version I installed on the host. No dice. I'm probably doing something silly stupid here, but wasn't sure where else to turn.

I can try the Docker Compose instructions and see if that works, but I've never used Docker Compose before so I was trying the simpler instructions first.

Thanks.

**Comment by jamalbernhard** [comment]
Solved using `--network="host"` in the `docker run` command.

**Comment by rashmi7321** [comment]
hi, while i am trying to deploy wiki.js using yaml files in kubernetes(in gcp(GKE)) its getting deployed but while i am trying to create user or save the documents getting "ERROR UNDEFINED". couldnot able to resolve it.
![error undefined](https://user-images.githubusercontent.com/37528399/59028148-73194600-8878-11e9-8b4f-cedf055509ef.JPG)

**Comment by rashmi7321** [comment]
@ @jamalbernhard @felipeplets @Savageman
 hi, while i am trying to deploy wiki.js using yaml files in kubernetes(in gcp(GKE)) its getting deployed but while i am trying to create user or save the documents getting "ERROR UNDEFINED". couldnot able to resolve it.
![error undefined](https://user-images.githubusercontent.com/37528399/59028588-87aa0e00-8879-11e9-8b64-f688e897e6a8.JPG)
