### ISSUE TITLE
Wiki cant be embedded as iframe

### ISSUE THREAD

**Issue by JanOesterh** [Requarks/wiki-v1#215]
### Story behind the Question
I tryed to embed my wiki.js as a tab in our crm system.
That works as an iframe.
When i try to open it there is just a white screen.

Is it that the wiki cant be embedded or something wrong configured in my network?

**Comment by NGPixel** [comment]
You'll need to remove this line to allow iframe embedding:

https://github.com/Requarks/wiki-v1/blob/19a5d0f10754f0a54448c1701eb10f1fd9e2a560/server/middlewares/security.js#L18

**Comment by JanOesterh** [comment]
Thanks for that quick solution.
It worked great!
