### ISSUE TITLE
Could not install the project on windows 7

### ISSUE THREAD

**Issue by m-ahmadi** [Requarks/wiki-v1#219]
**Question**
I tried to install the project on windows following the instructions from [this page](https://docs.requarks.io/wiki/install/installation#windows) where I got these 2 error message in my PowerShell window.

**Here's what I ran:**
`Set-ExecutionPolicy Bypass`

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://wiki.js.org/install.ps1'))`

**Here are the error messages:**
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enumeration values.
Specify one of the following enumeration values and try again.
The possible enumeration values are "Ssl3, Tls"."
At line:1 char:28
+ [Net.ServicePointManager]:: <<<< SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://wiki.js.org/install.ps1'))
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At line:1 char:135
+ [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString <<<< ('https://wiki.js.org/install.ps1'))
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

**Host Info:**
OS: [Windows 7]
Wiki.js version: [1.0.117]
Database engine: [mongo 4.0.2]

**Comment by NGPixel** [comment]
In an elevated powershell prompt:
```powershell
# For x64:
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

# For x86:
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord 
```

Then try again in a new powershell prompt.

**Comment by m-ahmadi** [comment]
I tried your solution and got the same 2 error messages.
still unable to install.

**Comment by NGPixel** [comment]
Then I suggest downloading the script manually and executing it locally:

https://wiki.js.org/install.ps1

**Comment by m-ahmadi** [comment]
I downloaded the script and ran:
`powershell -executionpolicy bypass -File .\install.ps1`
and
`Set-ExecutionPolicy Bypass`
`powershell -File install.ps1`

both in normal and elavated prompts, and here are the error messages:

![issue](https://user-images.githubusercontent.com/16363767/59969407-cc17f800-9561-11e9-94ba-e2f50aca57d8.png)



`Exception setting "SecurityProtocol": "Cannot convert value "tls12, tls11, tls" to type "System.Net.SecurityProtocolType" due to invalid enumeration values. Specify on
e of the following enumeration values and try again. The possible enumeration values are "Ssl3, Tls"."
At C:\install.ps1:1 char:28
+ [Net.ServicePointManager]:: <<<< SecurityProtocol = "tls12, tls11, tls"
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Add-Type : Cannot add type. The assembly 'System.IO.Compression.FileSystem' could not be found.
At C:\install.ps1:2 char:9
+ Add-Type <<<<  -AssemblyName System.IO.Compression.FileSystem
    + CategoryInfo          : ObjectNotFound: (System.IO.Compression.FileSystem:String) [Add-Type], Exception
    + FullyQualifiedErrorId : ASSEMBLY_NOT_FOUND,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. One or more required assemblies are missing.
At C:\install.ps1:2 char:9
+ Add-Type <<<<  -AssemblyName System.IO.Compression.FileSystem
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : ASSEMBLY_LOAD_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

 __    __ _ _    _    _
/ / /\ \ (_) | _(_)  (_)___
\ \/  \/ / | |/ / |  | / __|
 \  /\  /| |   <| |_ | \__ \
  \/  \/ |_|_|\_\_(_)/ |___/
                   |__/
   < INSTALL >

Specify the full path where Wiki.js should be installed (e.g. C:\wiki):
Path: C:\wiki
[1/6] Fetching 7zip helper... OK
[2/6] Fetching latest build... Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At C:\install.ps1:62 char:25
+ $downloader.DownloadFile <<<< ("https://github.com/Requarks/wiki-v1/releases/download/v$VERSION/wiki-js.tar.gz", "$curPath\wiki-js.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

OK
[3/6] Fetching dependencies... Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At C:\install.ps1:66 char:25
+ $downloader.DownloadFile <<<< ("https://github.com/Requarks/wiki-v1/releases/download/v$VERSION/node_modules.tar.gz", "$curPath\node_modules.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

OK
[4/6] Extracting app files...
ERROR: The system cannot find the file specified.
C:\wiki\wiki-js.tar.gz



System ERROR:
The system cannot find the file specified.
Error: 7-Zip encountered a fatal error while extracting the files
At C:\install.ps1:46 char:14
+     2 { throw <<<<  "Error: 7-Zip encountered a fatal error while extracting the files" }
    + CategoryInfo          : OperationStopped: (Error: 7-Zip en...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Error: 7-Zip encountered a fatal error while extracting the files`

**Comment by NGPixel** [comment]
It seems like your version of Windows is too old for this script. Try installing the app manually:

- Download both:
https://github.com/Requarks/wiki-v1/releases/download/v1.0.117/wiki-js.tar.gz
and
https://github.com/Requarks/wiki-v1/releases/download/v1.0.117/node_modules.tar.gz

- Extract the contents of `wiki-js.tar.gz` to a folder of your choice.
- Extract the contents of `node_modules.tar.gz` to that same folder.
- Rename `config.sample.yml` to `config.yml`
- Run `node wiki configure`

**Comment by m-ahmadi** [comment]
> It seems like your version of Windows is too old for this script. Try installing the app manually:
> 
> * Download both:
>   https://github.com/Requarks/wiki-v1/releases/download/v1.0.117/wiki-js.tar.gz
>   and
>   https://github.com/Requarks/wiki-v1/releases/download/v1.0.117/node_modules.tar.gz
> * Extract the contents of `wiki-js.tar.gz` to a folder of your choice.
> * Extract the contents of `node_modules.tar.gz` to that same folder.
> * Rename `config.sample.yml` to `config.yml`
> * Run `node wiki configure`

My Windows version is: `Windows 7 Ultimate Service Pack 1`

This solution worked and I was able to install and use the project. Thanks a lot!
