### ISSUE TITLE
Baseurl

### ISSUE THREAD

**Issue by wildskyf** [Requarks/wiki-v1#228]
### Actual behavior

My wikijs is hosed at url like this: `https://example.com/wiki`. We could find homepage at that url. When I click the `Create Home Page`, it will be navigated to `https://example.com/create/home`.

### Expected behavior

When I click the `Create Home Page`, it will be navigated to `https://example.com/wiki/create/home`.

### Steps to reproduce the behavior

Described above.

**Comment by NGPixel** [comment]
Subfolder installations are not supported. Use a subdomain instead.
