### ISSUE TITLE
Disallow public acces

### ISSUE THREAD

**Issue by Jaxophon** [Requarks/wiki-v1#248]
### Actual behavior
Ive searched the whole wiki! I cant find any setting about disallowing access to the public.
### Expected behavior
I want to disallow my wiki to the public

**Comment by NGPixel** [comment]
Change the `public` value to false in your config.yml file

**Comment by Jaxophon** [comment]
I have no public path in my config.yml

**Comment by Jaxophon** [comment]
Really? Its not possible to hide it?

**Comment by NGPixel** [comment]
https://github.com/Requarks/wiki-v1/blob/28e3f7604416acc22947055fcc9a4a3cd8027e0c/config.sample.yml#L59

**Comment by Jaxophon** [comment]
What? I cant find it. Its not the config with the mysql login data, right?

**Comment by Jaxophon** [comment]
I just added it and restarted it. It dosnt work

**Comment by NGPixel** [comment]
Why are you posting in the v1 project when clearly you're using v2?

https://docs.requarks.io/groups#private-wiki

**Comment by Jaxophon** [comment]
bro im so sorry. Thanks it works. You save my life
