### ISSUE TITLE
Folders Listing lacking Scroll Bar in Image Upload

### ISSUE THREAD

**Issue by coom** [Requarks/wiki-v1#250]
**Describe the bug**
Media Folders beyond a certain count that is dependent upon resolution are inaccessible due to lack of scroll bar. (See attached image for example)

**To Reproduce**
1. Install lastest WikiJS 1.X edition
2. Create a new page
3. Click on "Upload picture"
4. Create a lot of folders

**Expected behavior**
Click and drag a scroll bar to see additional folders.

**Screenshots**
![2020-01-15_15h18_44](https://user-images.githubusercontent.com/10179617/72441184-82ffed80-37aa-11ea-82f6-acadbe0c3a0c.png)

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.1]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
Don't post the same issue twice.

**Comment by coom** [comment]
Hi,I did not, I think it's a bug..Regards,Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Nicolas Giard <notifications@github.com> Date : 15/01/2020  19:16  (GMT+01:00) À : Requarks/wiki-v1 <wiki-v1@noreply.github.com> Cc : coom <coom@e-odyssey.net>, Author <author@noreply.github.com> Objet : Re: [Requarks/wiki-v1] Folders Listing lacking Scroll Bar in Image Upload (#250) Don't post the same issue twice.
