### ISSUE TITLE
git sync not working as understood

### ISSUE THREAD

**Issue by hexbinedit** [Requarks/wiki-v1#255]
### New files added to the git repository are not having pages built:

New files added to the git repository are not having pages built for them in the wiki. Likewise, removal of files is not represented in the pages on the GUI. Changes to existing files that are then synced are propagating into the wiki just fine.

### New markdown files

New markdown files added under new directories in the repo, created on a separate branch, are merged to the master and then synced with the wiki. Said new files should have pages built for them.

### git add, commit, push, subsequent merge.
Am I misunderstanding the purpose of the git sync functionality. The new pages are propogated into the local repo and I can use the option to import everything to add the new files, but this is not a feature I want to hand out. Plus with files being removed from the repo, why can't the wiki determine that the page should be removed? What should the expected functionality be?

Thank you for your time!

**Comment by NGPixel** [comment]
New files should result in new pages being created. Make sure they respect the kebab-case naming format.

**Comment by hexbinedit** [comment]
How are files then removed? Does it just take some time to propagate those additions to pages as well?

**Comment by NGPixel** [comment]
Sync runs every 5 mins.

**Comment by hexbinedit** [comment]
And I've used force sync to speed things up. The changes to existing pages are immediate, but new files do not have pages built for them using kebab format and .md extension. I have to manually 'import everything' to get the pages to show up. Again, sorry if I'm misunderstanding something.
