### ISSUE TITLE
Move/rename and Duplicate page always greyed out

### ISSUE THREAD

**Issue by stefaanMLB** [Requarks/wiki-v1#256]
Under administration / pages / actions these choices are greyed out for all pages
- Re-render
- Unpublish
- Duplicate
- Move/rename

![image](https://user-images.githubusercontent.com/50827063/85529695-9e024380-b60d-11ea-90cd-e9abdcee3b7c.png)

I'd like to rename a page, how can I activate the rename option ?

**Comment by NGPixel** [comment]
Rename from the page itself, not from the admin.
