### ISSUE TITLE
Upload Not Completing

### ISSUE THREAD

**Issue by ddlidded** [Requarks/wiki-v1#260]
### Actual behavior

When uploading an image-based asset through the browse -> upload method, it gets to 100% but does not complete and does not get uploaded successfully.

When checking my application logs, this is a message that is displayed:
**warn: Cannot read properties of undefined (reading 'toLowerCase')**

If it helps, this issue was not occurring a day or two ago and was working fine.

**Comment by NGPixel** [comment]
This isn't the correct repository. This is for v1, not v2.

The issue you're mentioning is already fixed.

**Comment by ddlidded** [comment]
Sorry I meant to put this in the v2 wiki.
